name = "thermalfunctions"
version = "0.1.0"
license = "license"
author = "Thomas"
maintainer = "thomas.biekoetter@desy.de"
copyright = "Copyright 2025, Thomas"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
[install]
library = true
test = false
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"
[dependencies]
cubicsplines = { git = "https://github.com/thomasbiekoetter/cubicsplines.git" }
quadpack = { git = "https://github.com/thomasbiekoetter/quadpack.git" }

